#!/bin/zsh

# check if 'dotfiles' was cloned into the correct directory
if [ ! -d "${HOME}/Workspace/dotfiles" ]; then
  echo "[macos.sh](error): 'dotfiles' must be cloned into the '${HOME}/Workspace' directory"
  exit 1
fi

# install homebrew
echo "[macos.sh](info) installing homebrew..."
/bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "[macos.sh](info) finished installing homebrew"

# install brew packages
echo "[macos.sh](info) installing brew packages..."
brew install autojump bat ffmpeg git gnupg jq neofetch nmap ranger ripgrep wifi-password yt-dlp
echo "[macos.sh](info) finished installing brew packages"

# install brew casks
echo "[macos.sh](info) installing brew casks..."
brew install --cask kitty macvim nightfall raycast
echo "[macos.sh](info) finished installing brew casks"

# install oh-my-zsh
echo "[macos.sh](info) installing oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
zshrc = "${HOME}/.zshrc"
if [ -e "$zshrc" ]; then
    rm "$zshrc"
    echo "[macos.sh](info) removed default '.zshrc' generated by oh-my-zsh installation"
fi
echo "[macos.sh](info) finished installing oh-my-zsh"

# alias dotfiles
echo "[macos.sh](info) creating aliases for all dotfiles..."
ln -s "${HOME}/Workspace/dotfiles/.zshrc" "${HOME}/.zshrc"
ln -s "${HOME}/Workspace/dotfiles/.vimrc" "${HOME}/.vimrc"
ln -s "${HOME}/Workspace/dotfiles/.gitconfig" "${HOME}/.gitconfig"
ln -s "${HOME}/Workspace/dotfiles/.ssh/config" "${HOME}/.ssh/config"
echo "[macos.sh](info) finished creating aliases for all dotfiles"

# clone and alias scripts
echo "[macos.sh](info) cloning and aliasing user scripts..."
git clone git@github.com:richardszegh/scripts.git ${HOME}/Workspace/scripts
chmod +x ${HOME}/Workspace/scripts/*
source ${HOME}/.zshrc
echo "[macos.sh](info) finished cloning and aliasing user scripts"
